In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
california = fetch_california_housing()

In [3]:
california

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]]),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894]),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n

In [4]:
print(california.DESCR)

.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

    :Number of Instances: 20640

    :Number of Attributes: 8 numeric, predictive attributes and the target

    :Attribute Information:
        - MedInc        median income in block group
        - HouseAge      median house age in block group
        - AveRooms      average number of rooms per household
        - AveBedrms     average number of bedrooms per household
        - Population    block group population
        - AveOccup      average number of household members
        - Latitude      block group latitude
        - Longitude     block group longitude

    :Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived

In [5]:
california.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'feature_names', 'DESCR'])

In [6]:
california.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [7]:
california.target

array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894])

In [8]:
california.data

array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]])

In [9]:
california.frame

In [10]:
california.target_names

['MedHouseVal']

In [11]:
import pandas as pd
import numpy as np
import seaborn as sns 
import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
df = pd.DataFrame(california.data,columns=[california.feature_names])

In [13]:
df['Price'] = california.target

In [14]:
df.head()

MedInc HouseAge  AveRooms AveBedrms Population  AveOccup Latitude  \
0  8.3252     41.0  6.984127  1.023810      322.0  2.555556    37.88   
1  8.3014     21.0  6.238137  0.971880     2401.0  2.109842    37.86   
2  7.2574     52.0  8.288136  1.073446      496.0  2.802260    37.85   
3  5.6431     52.0  5.817352  1.073059      558.0  2.547945    37.85   
4  3.8462     52.0  6.281853  1.081081      565.0  2.181467    37.85   

  Longitude  Price  
0   -122.23  4.526  
1   -122.22  3.585  
2   -122.24  3.521  
3   -122.25  3.413  
4   -122.25  3.422

In [15]:
## DIVIDING THE DATA SET INTO THE DEPENDENT AND INDEPENDENT FEATURE

In [16]:
X = df.iloc[:,:-1]

In [17]:
X

MedInc HouseAge  AveRooms AveBedrms Population  AveOccup Latitude  \
0      8.3252     41.0  6.984127  1.023810      322.0  2.555556    37.88   
1      8.3014     21.0  6.238137  0.971880     2401.0  2.109842    37.86   
2      7.2574     52.0  8.288136  1.073446      496.0  2.802260    37.85   
3      5.6431     52.0  5.817352  1.073059      558.0  2.547945    37.85   
4      3.8462     52.0  6.281853  1.081081      565.0  2.181467    37.85   
...       ...      ...       ...       ...        ...       ...      ...   
20635  1.5603     25.0  5.045455  1.133333      845.0  2.560606    39.48   
20636  2.5568     18.0  6.114035  1.315789      356.0  3.122807    39.49   
20637  1.7000     17.0  5.205543  1.120092     1007.0  2.325635    39.43   
20638  1.8672     18.0  5.329513  1.171920      741.0  2.123209    39.43   
20639  2.3886     16.0  5.254717  1.162264     1387.0  2.616981    39.37   

      Longitude  
0       -122.23  
1       -122.22  
2       -122.24  
3       -122.25  
4       -122.25  
...         ...  
20635   -121.09  
20636   -121.21  
20637   -121.22  
20638   -121.32  
20639   -121.24  

[20640 rows x 8 columns]

In [18]:
y = df.iloc[:,-1]

In [19]:
y

0        4.526
1        3.585
2        3.521
3        3.413
4        3.422
         ...  
20635    0.781
20636    0.771
20637    0.923
20638    0.847
20639    0.894
Name: (Price,), Length: 20640, dtype: float64

In [20]:
## TRAINING AND SPLITING 
from sklearn.model_selection import train_test_split

In [21]:
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.3,random_state=42)

In [22]:
X_train.shape

(14448, 8)

In [23]:
X_test.shape

(6192, 8)

In [24]:
y_train.shape

(14448,)

In [25]:
y_test.shape

(6192,)

In [26]:
## FEATURE SCALING
from sklearn.preprocessing import StandardScaler

In [27]:
scaler = StandardScaler()

In [69]:
X_train_scaled = scaler.fit_transform(X_train)

In [70]:
X_train_scaled

array([[ 0.13350629,  0.50935748,  0.18106017, ..., -0.01082519,
        -0.80568191,  0.78093406],
       [-0.53221805, -0.67987313, -0.42262953, ..., -0.08931585,
        -1.33947268,  1.24526986],
       [ 0.1709897 , -0.36274497,  0.07312833, ..., -0.04480037,
        -0.49664515, -0.27755183],
       ...,
       [-0.49478713,  0.58863952, -0.59156984, ...,  0.01720102,
        -0.75885816,  0.60119118],
       [ 0.96717102, -1.07628333,  0.39014889, ...,  0.00482125,
         0.90338501, -1.18625198],
       [-0.68320166,  1.85715216, -0.82965604, ..., -0.0816717 ,
         0.99235014, -1.41592345]])

In [71]:
X_test_scaled= scaler.transform(X_test)

In [72]:
X_test_scaled

array([[-1.1526893 , -0.28346293, -0.50781822, ...,  0.06127763,
         0.19166399,  0.28664112],
       [-0.70640568,  0.11294728, -0.16252032, ..., -0.03551561,
        -0.23911452,  0.06196251],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.14215427,
         1.00639726, -1.42590916],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ..., -0.06058827,
        -0.92742367,  0.8358555 ],
       [-0.11911302, -1.47269353,  0.02607207, ...,  0.03461374,
         1.01576201, -0.84673764],
       [-0.43304974, -0.91771925, -0.84872893, ..., -0.0407528 ,
        -0.70266966,  0.67109119]])

In [32]:
## MODEL TRANING
from sklearn.linear_model import LinearRegression

In [33]:
regressor = LinearRegression()

In [73]:
regressor.fit(X_train_scaled,y_train)

LinearRegression()

In [74]:
regressor.intercept_

2.0692396089424143

In [75]:
regressor.coef_

array([ 8.49221760e-01,  1.22119309e-01, -2.99558449e-01,  3.48409673e-01,
       -8.84488134e-04, -4.16980388e-02, -8.93855649e-01, -8.68616688e-01])

In [76]:
y_pred = regressor.predict(X_test_scaled)

In [77]:
y_pred

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [78]:
## PERFORMANCE METRICS COST FUNCTION
from sklearn.metrics import mean_absolute_error,mean_squared_error

In [79]:
print('MAE:' ,mean_absolute_error(y_test,y_pred))

MAE: 0.5272474538305952


In [80]:
print('MSE:',mean_squared_error(y_test,y_pred))

MSE: 0.5305677824766752


In [81]:
import numpy as np

In [82]:
print('RMSE:' , np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE: 0.7284008391515452


In [83]:
## CALCULATING THE ACCURACY OF THE MODEL 
from sklearn.metrics import r2_score

In [84]:
score = r2_score(y_test,y_pred)

In [85]:
score  ## R-SQUARE 

0.5957702326061664

In [86]:
## ADJUSTED R-SQUARE

In [88]:
1 - (1-score)*(len(y_test)-1)/(len(y_test)-X_test.shape[1]-1)

0.5952472117200025

In [89]:
df.head(50)

MedInc HouseAge  AveRooms AveBedrms Population  AveOccup Latitude  \
0   8.3252     41.0  6.984127  1.023810      322.0  2.555556    37.88   
1   8.3014     21.0  6.238137  0.971880     2401.0  2.109842    37.86   
2   7.2574     52.0  8.288136  1.073446      496.0  2.802260    37.85   
3   5.6431     52.0  5.817352  1.073059      558.0  2.547945    37.85   
4   3.8462     52.0  6.281853  1.081081      565.0  2.181467    37.85   
5   4.0368     52.0  4.761658  1.103627      413.0  2.139896    37.85   
6   3.6591     52.0  4.931907  0.951362     1094.0  2.128405    37.84   
7   3.1200     52.0  4.797527  1.061824     1157.0  1.788253    37.84   
8   2.0804     42.0  4.294118  1.117647     1206.0  2.026891    37.84   
9   3.6912     52.0  4.970588  0.990196     1551.0  2.172269    37.84   
10  3.2031     52.0  5.477612  1.079602      910.0  2.263682    37.85   
11  3.2705     52.0  4.772480  1.024523     1504.0  2.049046    37.85   
12  3.0750     52.0  5.322650  1.012821     1098.0  2.346154    37.85   
13  2.6736     52.0  4.000000  1.097701      345.0  1.982759    37.84   
14  1.9167     52.0  4.262903  1.009677     1212.0  1.954839    37.85   
15  2.1250     50.0  4.242424  1.071970      697.0  2.640152    37.85   
16  2.7750     52.0  5.939577  1.048338      793.0  2.395770    37.85   
17  2.1202     52.0  4.052805  0.966997      648.0  2.138614    37.85   
18  1.9911     50.0  5.343675  1.085919      990.0  2.362768    37.84   
19  2.6033     52.0  5.465455  1.083636      690.0  2.509091    37.84   
20  1.3578     40.0  4.524096  1.108434      409.0  2.463855    37.85   
21  1.7135     42.0  4.478142  1.002732      929.0  2.538251    37.85   
22  1.7250     52.0  5.096234  1.131799     1015.0  2.123431    37.84   
23  2.1806     52.0  5.193846  1.036923      853.0  2.624615    37.84   
24  2.6000     52.0  5.270142  1.035545     1006.0  2.383886    37.84   
25  2.4038     41.0  4.495798  1.033613      317.0  2.663866    37.85   
26  2.4597     49.0  4.728033  1.020921      607.0  2.539749    37.85   
27  1.8080     52.0  4.780856  1.060453     1102.0  2.775819    37.85   
28  1.6424     50.0  4.401691  1.040169     1131.0  2.391121    37.84   
29  1.6875     52.0  4.703226  1.032258      395.0  2.548387    37.84   
30  1.9274     49.0  5.068783  1.182540      863.0  2.283069    37.84   
31  1.9615     52.0  4.882086  1.090703     1168.0  2.648526    37.84   
32  1.7969     48.0  5.737313  1.220896     1026.0  3.062687    37.84   
33  1.3750     49.0  5.030395  1.112462      754.0  2.291793    37.83   
34  2.7303     51.0  4.972015  1.070896     1258.0  2.347015    37.83   
35  1.4861     49.0  4.602273  1.068182      570.0  2.159091    37.83   
36  1.0972     48.0  4.807487  1.155080      987.0  2.639037    37.83   
37  1.4103     52.0  3.749380  0.967742      901.0  2.235732    37.83   
38  3.4800     52.0  4.757282  1.067961      689.0  2.229773    37.83   
39  2.5898     52.0  3.494253  1.027299     1377.0  1.978448    37.83   
40  2.0978     52.0  4.215190  1.060759      946.0  2.394937    37.83   
41  1.2852     51.0  3.759036  1.248996      517.0  2.076305    37.83   
42  1.0250     49.0  3.772487  1.068783      462.0  2.444444    37.84   
43  3.9643     52.0  4.797980  1.020202      467.0  2.358586    37.84   
44  3.0125     52.0  4.941781  1.065068      660.0  2.260274    37.83   
45  2.6768     52.0  4.335079  1.099476      718.0  1.879581    37.83   
46  2.0260     50.0  3.700658  1.059211      616.0  2.026316    37.83   
47  1.7348     43.0  3.980237  1.233202      558.0  2.205534    37.82   
48  0.9506     40.0  3.900000  1.218750      423.0  2.643750    37.82   
49  1.7750     40.0  2.687500  1.065341      700.0  1.988636    37.82   

   Longitude  Price  
0    -122.23  4.526  
1    -122.22  3.585  
2    -122.24  3.521  
3    -122.25  3.413  
4    -122.25  3.422  
5    -122.25  2.697  
6    -122.25  2.992  
7    -122.25  2.414  
8    -122.26  2.267  
9    -122.25  2.611  
10   -122.26  2.815  
11   -122.26  2.

In [90]:
scaled_values  = scaler.transform([[7.15,46,8.2,2.5,555,3.22,45.8,-122.25]])   ## NEW DATA POINTS ARE GIVEN

In [91]:
scaled_values

array([[   7.15,   46.  ,    8.2 ,    2.5 ,  555.  ,    3.22,   45.8 ,
        -122.25]])

In [92]:
scaled_values[0]

array([   7.15,   46.  ,    8.2 ,    2.5 ,  555.  ,    3.22,   45.8 ,
       -122.25])

In [93]:
regressor.predict([scaled_values[0]])

array([76.79795108])

In [94]:
import pickle

In [95]:
pickle.dump(scaler,open('scaler.pkl','wb'))
pickle.dump(regressor,open('regressor.pkl','wb'))

In [109]:
model_regressor = pickle.load(open('regressor.pkl','rb'))
model_regressor.predict(X_test_scaled)

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [110]:
standard_scaler = pickle.load(open('scaler.pkl','rb'))

In [111]:
standard_scaler.transform(X_test_scaled)

array([[-1.1526893 , -0.28346293, -0.50781822, ...,  0.06127763,
         0.19166399,  0.28664112],
       [-0.70640568,  0.11294728, -0.16252032, ..., -0.03551561,
        -0.23911452,  0.06196251],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.14215427,
         1.00639726, -1.42590916],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ..., -0.06058827,
        -0.92742367,  0.8358555 ],
       [-0.11911302, -1.47269353,  0.02607207, ...,  0.03461374,
         1.01576201, -0.84673764],
       [-0.43304974, -0.91771925, -0.84872893, ..., -0.0407528 ,
        -0.70266966,  0.67109119]])

In [113]:
model_regressor.predict(standard_scaler.transform(X_test))

array([0.72604907, 1.76743383, 2.71092161, ..., 2.07465531, 1.57371395,
       1.82744133])

In [114]:
X_test

array([[-1.1526893 , -0.28346293, -0.50781822, ...,  0.06127763,
         0.19166399,  0.28664112],
       [-0.70640568,  0.11294728, -0.16252032, ..., -0.03551561,
        -0.23911452,  0.06196251],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.14215427,
         1.00639726, -1.42590916],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ..., -0.06058827,
        -0.92742367,  0.8358555 ],
       [-0.11911302, -1.47269353,  0.02607207, ...,  0.03461374,
         1.01576201, -0.84673764],
       [-0.43304974, -0.91771925, -0.84872893, ..., -0.0407528 ,
        -0.70266966,  0.67109119]])

In [115]:
X_test_scaled

array([[-1.1526893 , -0.28346293, -0.50781822, ...,  0.06127763,
         0.19166399,  0.28664112],
       [-0.70640568,  0.11294728, -0.16252032, ..., -0.03551561,
        -0.23911452,  0.06196251],
       [-0.20830675,  1.85715216, -0.59546738, ..., -0.14215427,
         1.00639726, -1.42590916],
       ...,
       [-0.19155996, -0.99700129, -0.6830438 , ..., -0.06058827,
        -0.92742367,  0.8358555 ],
       [-0.11911302, -1.47269353,  0.02607207, ...,  0.03461374,
         1.01576201, -0.84673764],
       [-0.43304974, -0.91771925, -0.84872893, ..., -0.0407528 ,
        -0.70266966,  0.67109119]])